### ISSUE TITLE
"Debug" mode support

### ISSUE THREAD

**Issue by dkoyro** [bootique/bootique-logback#24]
I'm sure it would be useful in diagnosing LogBack issues. 
All the details are there: http://logback.qos.ch/manual/configuration.html

As an idea: 
Under certain conditions `LogbackContextFactory` could register `OnConsoleStatusListener` instance in the `StatusManager`. 

Here is the example:

```
LogbackContextFactory.configLogbackContext() {
...
StatusListenerConfigHelper.addOnConsoleListenerInstance(context, new OnConsoleStatusListener());
...
}
```

**Comment by andrus** [comment]
Implemented. Controlling config property is `log.debugLogback`. Thanks for implementation hint.
