### ISSUE TITLE
Contribute own appenders

### ISSUE THREAD

**Issue by IRus** [bootique/bootique-logback#27]
Currently there is no way to add own appender to this module, for example i want to contribute Sentry appender.

**Comment by andrus** [comment]
You do not need to contribute a new appender to DI. You just need a custom factory. Look at ConsoleAppenderFactory or FileAppenderFactory for instance. All that is needed is `@JsonTypeName("newtype")`  annotation and adding a new type to your module's `io.bootique.config.PolymorphicConfiguration`
